server:
  port: 8080

spring:
  application:
    name: auth-service
  profiles:
    active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH:/api/v1/auth/v3/api-docs}
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis

  data:
    redis:
      port: 6379
      host: ${SPRING_DATA_REDIS_HOST:localhost}

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  security:
    jwt:
      secret: ${APPLICATION_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000
      issuer: esrakonya-auth-service

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    com.zaxxer.hikari: WARN
    org.esrakonya.backend: INFO

management:
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}