app:
  environment: prod
  message: Notification Service is running on Kubernetes Infrastructure

logging:
  level:
    org.springframework.kafka: WARN
    org.esrakonya.backend: INFO

logstash:
  host: ${LOGSTASH_HOST:marketplace-logstash}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
