apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-common-config
data:
  KAFKA_BROKERS: {{ .Values.global.config.kafkaBrokers | quote }}
  LOGSTASH_HOST: {{ .Values.global.config.logstashHost | quote }}
  ZIPKIN_URL: {{ .Values.global.config.zipkinUrl | quote }}
  POSTGRES_URL: {{ .Values.global.config.postgresUrl | quote }}