{{- range $key, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
    - protocol: TCP
      port: {{ $service.port }}
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: {{ printf "%s:%s" $service.image ($.Values.global.imageTag | default "latest") }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          env:
            # Sadece eğer 'env' tanımlıysa döngüye gir ✅
              {{- if $service.env }}
              {{- range $envKey, $envVal := $service.env }}
              - name: {{ $envKey }}
                value: {{ $envVal | quote }}
              {{- end }}
              {{- end }}
              - name: SPRING_PROFILES_ACTIVE
                value: "prod"
              - name: SPRING_DATASOURCE_URL
                value: "jdbc:postgresql://marketplace-postgres:5432/marketplace_db"
          ports:
            - containerPort: 8080
  {{- end }}