{{- range $key, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ $service.name }}
  ports:
    - protocol: TCP
      port: {{ $service.port }}
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: {{ if $.Values.global.imageTag }}{{ printf "%s:%s" $service.image $.Values.global.imageTag }}{{ else }}{{ $service.image }}{{ end }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: marketplace-common-config
                  key: KAFKA_BROKERS
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: LOGSTASH_HOST
              valueFrom:
                configMapKeyRef:
                  name: marketplace-common-config
                  key: LOGSTASH_HOST
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: marketplace-common-config
                  key: POSTGRES_URL
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: marketplace-common-config
                  key: ZIPKIN_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: postgres-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: postgres-password
            - name: APPLICATION_SECURITY_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: marketplace-secrets
                  key: jwt-secret
            {{- if $service.env }}
            {{- range $service.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
  {{- end }}