apiVersion: v1
kind: Secret
metadata:
  name: marketplace-secrets
type: Opaque
data:
  postgres-user: {{ .Values.global.secrets.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.global.secrets.postgresPassword | b64enc | quote }}
  jwt-secret: {{ .Values.global.secrets.jwtSecret | b64enc | quote }}