app:
  environment: prod
  message: Gateway is running on Kubernetes Infrastructure

management:
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}

logstash:
  host: ${LOGSTASH_HOST:marketplace-logstash}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.esrakonya.backend: INFO