app:
  environment: prod
  message: Gateway is running on Kubernetes Infrastructure

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL}
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}

# Inside application-prod.yml
LOGSTASH_HOST: ${LOGSTASH_HOST:marketplace-logstash}