# --- GLOBAL SETTINGS ---
global:
  imagePullPolicy: IfNotPresent
  namespace: default
  imageTag: ""
  config:
    kafkaBrokers: "marketplace-kafka:29092"
    logstashHost: "marketplace-logstash"
    zipkinUrl: "http://marketplace-zipkin:9411"
    postgresUrl: "jdbc:postgresql://marketplace-postgres:5432/marketplace_db"
  secrets:
    postgresUser: "esra"
    postgresPassword: ""
    jwtSecret: ""

# --- MICROSERVICES CONFIG ---
services:
  auth:
    name: auth-service
    image: esrakonya/auth-service
    port: 8080
  product:
    name: product-service
    image: esrakonya/product-service
    port: 8080
  gateway:
    name: gateway-service
    image: esrakonya/gateway-service
    port: 8080
    env:
      - name: AUTH_SERVICE_URL
        value: "http://auth-service:8080"
      - name: PRODUCT_SERVICE_URL
        value: "http://product-service:8080"
      - name: INVENTORY_SERVICE_URL
        value: "http://inventory-service:8080"
      - name: SPRINGDOC_API_DOCS_ENABLED
        value: "true"
  inventory:
    name: inventory-service
    image: esrakonya/inventory-service
    port: 8080
  notification:
    name: notification-service
    image: esrakonya/notification-service
    port: 8080

# --- INFRASTRUCTURE CONFIG ---
infrastructure:
  postgres:
    name: marketplace-postgres
    image: postgres:16-alpine
    dbName: marketplace_db
    user: esra
    password: ""
    pvcName: postgres-pvc
  redis:
    name: marketplace-redis
    image: redis:7-alpine
  kafka:
    name: marketplace-kafka
    image: confluentinc/cp-kafka:7.4.0
    zookeeper: marketplace-zookeeper

# --- OBSERVABILITY CONFIG ---
observability:
  zipkin:
    name: marketplace-zipkin
    image: openzipkin/zipkin:3
  elasticsearch:
    name: marketplace-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1