server:
  port: 0

app:
  environment: test
  message: Product Service Testing Environment

spring:
  cache:
    type: none
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    org.esrakonya.backend: DEBUG