server:
  port: 0

app:
  environment: test
  message: Product Service Testing Environment

spring:
  main:
    allow-bean-definition-overriding: true

  cache:
    type: none

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.testcontainers: INFO