server:
  port: 0

app:
  environment: test
  message: Inventory Service Testing Environment

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: never

  kafka:
    consumer:
      group-id: test-group-inventory-${random.uuid}

logging:
  level:
    org.esrakonya.backend: DEBUG