app:
  environment: prod
  message: Inventory Service is running on Docker

spring:
  datasource:
  jpa:
    show-sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:marketplace-redis}

logging:
  level:
    org.hibernate.SQL: WARN
    org.esrakonya.backend: INFO

logstash:
  host: ${LOGSTASH_HOST:marketplace-logstash}